CREATE DATABASE amazonebooks_external;

USE amazonebooks_external;

CREATE SCHEMA CONFIG;

USE SCHEMA CONFIG;

CREATE OR REPLACE TRANSIENT TABLE CONFIG.TABLE_CONFIG (
	TABLE_NAME TEXT,
	LAST_EXTRACT_DATE DATE
);

CREATE OR REPLACE TRANSIENT TABLE CONFIG.TBL_PRIMARY_KEY (
	TABLE_NAME TEXT,
	PRIMARY_COLUMN TEXT,
	ORDINAL_POSITION NUMBER(38,0),
	STAGE_POSITION NUMBER(38,0)
);

-- CREATING STORAGE INTEGRATION 

CREATE OR REPLACE STORAGE INTEGRATION ACCESS_TO_S3BUCKET
TYPE=EXTERNAL_STAGE
STORAGE_PROVIDER='S3'
STORAGE_AWS_ROLE_ARN='arn:aws:iam::<account-no>:role/S3_read_access_for_snowflake'
ENABLED=TRUE
STORAGE_ALLOWED_LOCATIONS=('s3://lz-snowflake/Snowflake/');